### ISSUE TITLE
Matching on request body

### ISSUE THREAD

**Issue by stevegraham** [parroty/exvcr#22]
Just opening an issue to start discussion of this feature. Is it something you've thought of? Would you be open to a PR?

**Comment by parroty** [comment]
Thank for the comment, and sorry being late to respond (overlooked this item). 

Having the body matching would be one option. It was one of the possible options when query param matching is added at https://github.com/parroty/exvcr/issues/11, but just didn't go further at the moment.

**Comment by nurugger07** [comment]
Are you working this @stevegraham? I'm in need of this feature and can work on a PR today if that's ok with @parroty

**Comment by parroty** [comment]
I haven't been able to work on this item and PR would be great.

**Comment by nurugger07** [comment]
@parroty When working on this I also noticed specific header matching wasn't implemented yet, including checks on content-type. I wouldn't mind creating an issue for this and providing a PR if you don't mind.

**Comment by parroty** [comment]
Thanks for the PR. I'm playing around the updated version (#29) and wondering it might be good to have this matching as optional rather than always enable it (as similar as `match_requests_on: [:query]`. What do you think?

https://github.com/parroty/exvcr#matching-against-query-params

As long as it's optional adding further checking (ex. Content-Type), that would be great.

Maybe I haven't been able to play around enough and please let me do during the weekend (before the hex update).

**Comment by nurugger07** [comment]
@parroty I had a similar discussion with my team and my argument was if you are passing a request body it should match the stubbed cassette otherwise the request would be invalid. That being said I see that this is a breaking change so I would agree that maybe `match_req_body: [:request_body]` would be preferable.

As far as header checking thoughts on `match_headers_on: [:headers]`?

**Comment by parroty** [comment]
Thanks for the discussion, stubbed one may be ok, but automatically recorded one can be unintentionally breaking.

I think the current `match_requests_on` are accepting list of atoms, so what about adding to them? If all  of them are specified, that would be `match_requests_on: [:query, :request_body, :headers]`.

**Comment by parroty** [comment]
(I should have clarified about options in the beginning, but I was forgetting some parts :sweat_smile:)

**Comment by parroty** [comment]
I tried to add `match_requests_on [:request_body]` as above. 
Does it make sense? (If it's OK, I'll be releasing hex package).

**Comment by parroty** [comment]
As the original testing of #29 remain working, I'm pushing it as v0.5.1. If there's remaining issue, please reopen or open another one (header matching is great too).

**Comment by nurugger07** [comment]
Sweet! Sorry I've been busy traveling this week. ElixirConf & all. I'll look at headers next
